server:
  port: 41022

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: #在此处配置要绑定的rabbitmq的服务信息
        defaultRabbit: #表示定义的名称，用于binding整合
          type: rabbit #消息组件类型
          environment: #设置rabbitmq的相关环境变量
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: #服务的整合处理
        input: #通道名字
          destination: studyExchange #要使用的交换机名称定义
          content-type: application/json #设置消息类型，本次为json，文本设置为"text/plain"
          binder: defaultRabbit #设置要绑定的消息服务的具体设置
          group: dbdj1201_stream_consumer
eureka:
  client:
    service-url:
      defaultZone: http://eureka9230.com:9230/eureka
  instance:
    instance-id: receive-41022.com
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true