server:
  port: 40999
spring:
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: localhost:8080
        #默认8719端口，假如被占用会自动递增+1，直至找到可用端口
        port: 8719
  application:
    name: nacos-order-consumer

#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'

#消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者)
service-url:
  nacos-user-service: http://nacos-payment-provider
# 激活sentinel对feign的支持
feign:
  sentinel:
    enabled: true