server:
  port: 9257

spring:
  application:
    name: service-gateway
  #  cloud: 固定路由
  #    gateway:
  #      routes:
  #        - id: payment_routh           #路由的ID，没有固定规则但要求唯一，建议配合服务名
  #          uri: http://localhost:9231  #匹配后提供服务的路由地址
  #          predicates:
  #            - Path=/payment/get/**    #断言：路径相匹配的进行路由
  #        - id: payment-routh2          #路由的ID，没有固定规则，但要求唯一，建议配合服务名
  #          uri: http://localhost:9231  #匹配后提供服务的路由地址
  #          predicates:
  #            - Path=/payment/lb/**      #断言，路径相匹配的进行路由
  #动态路由，船新玩法
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true             #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment-routh
          uri: lb://service-payment
          predicates:
            - Path=/payment/get/**
        - id: payment-routh2
          uri: lb://service-payment
          predicates:
            - Path=/payment/lb/**
  devtools:
    restart:
      poll-interval: 3000ms
      quiet-period: 2999ms

eureka:
  client:
    service-url:
      defaultZone: http://eureka9230.com:9230/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: gateway9527
    #    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    hostname: cloud-gateway-service
