server:
  port: 9232
spring:
  application:
    name: service-payment
  devtools:
    restart:
      poll-interval: 3000ms
      quiet-period: 2999ms
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql//localhost:3306/db_player?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
    username: root
    password: root
    url: jdbc:mysql:///db_player?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT&allowPublicKeyRetrieval=true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.dbdj1201.player.common.entities
eureka:
  client:
    service-url:
      defaultZone: http://eureka9230.com:9230/eureka,http://eureka9229.com:9229/eureka #集群
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    instance-id: payment9232
    prefer-ip-address: true